namespace Coursework_Master_Degree.ScriptableObjects.Items.Types
{
    public enum ItemType
    {
        Computing,
            // Laptop,
            // PC,
            // Smartphone,
            // Tablet,
        Consumables,
            // AdhesiveSpray,
            // CleaningSpray,
            // Rag,
        FFF,
            PrinterModels,
                PrusaMK4S,
                    Enclosure,
                    Parts,
                        // :enclosure
                        // FireSuppresionTube,
                        // HEPAFilterFan,
                        // HEPAFilterTrap,
                        // Thermometer,
                        // :printer
                        // AxisBelt,
                        // AxisBeltBearing,
                        // AxisGuideBearing,
                        // AxisRotor,
                        // AxisRotorBearing,
                        // BatteryCloset,
                        // BatteryClosetAdapter,
                        // ExtruderFanFrame,
                        // ExtruderFilamentBearing,
                        // ExtruderFilamentHeater,
                        // ExtruderNozzle,
                        // ExtrderThermistor,
                        // PrintBed,
                        // PrintBedThermistor,
                        // PrintPlate,
                    Printer,
                    Spool,
                        // :type
                        ABS,
                        PETG,
                        PLA,
                        TPU,
                        // :color
                        // Red,
                        // Green,
                        // Blue,
                        // Magenta,
                        // Yellow,
        Power,
            // ExtensionCord,
            // FluorescentLamp,
            // LEDLamp,
            // WallSocket,
            // WallSwitch,
        Surface,
            // RackShort,
            // RackWide,
            // TableShort,
            // TableWide,
            // ToolChestShort,
            // ToolChestWide,
        Tools,
            // SandingPaper,
            // SandingTool,
            // SeparatorBlade,
            // SupportCuttingTool,
    }
}